### PR TITLE
Update website content to support final project submission form

### PR DESCRIPTION
**Pull request by MarkBennett**
I've taken a lot of content that was previously in the final project submission form and moved it over to the website.

Note to @ajyong and @MandyMeindersma that I'm bad at dates and said sponsors had until May 30th to get us funds, with money going out in June. May ends of the 31st so this PR reflects that. ;)

### CODE REVIEW

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MarkBennett** [comment]
Just made one last minute tweak to the buttons at the top of the homepage @MandyMeindersma.

Can I get another quick review?

**Comment by MandyMeindersma** [comment]
Sorry I am on mobile and already in bed.

**Comment by MarkBennett** [comment]
> Sorry I am on mobile and already in bed.

Sounds like you're smarter than me than! Talk in the AM @MandyMeindersma!

**Comment by MarkBennett** [comment]
These changes will be going out shortly. Please review if you're able, otherwise I'll merge so we can announce the final submission form.

**Review by MandyMeindersma — APPROVED** [review]

**Pull request merged**
