### PR TITLE
add our story

### PR DESCRIPTION
**Pull request by pborlongan**
from Mandy's comment on [ch219]

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
hmm why did this change all the indenting?

**Comment by pborlongan** [comment]
I'm working on it right now, prettier is screwing it up haha.

**Comment by MandyMeindersma** [comment]
Ah sorry I am being picky. 

We are talking in the meeting about how many sections we have and we should probably have less text. I think we should change the first text copy. 

### we have:

With the COVID-19 pandemic in full swing, many people are looking at a lot of free time stuck indoors. Avoid cabin fever and use that time to make a difference in your community and the fight against COVID-19 by joining CODEVID-19, the world’s first pandemic hackathon!

The purpose of the hackathon ultimately isn’t to win prizes, it’s to build useful apps that people can use to manage and survive during the COVID-19 pandemic. Like the COVID-19 situation, the hackathon's resources and structure will change to better serve everyone who is a part of it!

The first prize (called the first responder prize) will be awarded March 24th and there will be many more to come!

### maybe change to:



With the COVID-19 pandemic in full swing, many people are looking at a lot of free time stuck indoors. Avoid cabin fever and use that time to make a difference in your community and the fight against COVID-19 by joining CODEVID-19, a pandemic hackathon!

The purpose of the hackathon ultimately isn’t to win prizes, it’s to build useful apps that people can use to manage and survive during the COVID-19 pandemic. ~Like the COVID-19 situation, the hackathon's resources and structure will change to better serve everyone who is a part of it!~ **What started in Edmonton, Canada as a discussion amongst developers on the Dev Edmonton Society Slack has exploded into a global initiative to improve people's quality of live and fight the COVID-19 pandemic.**

~The first prize (called the first responder prize) will be awarded March 24th and there will be many more to come!~ **With participants in over 10 countries around world, it's a growing movement. Do your part and join the fight now!**

**Comment by pborlongan** [comment]
No worries. Will do the change now!

**Comment by MandyMeindersma** [comment]
Sorry, I should have gotten that to you sooner. 
Thank you

**Pull request merged**
