### PR TITLE
Final winners blog post

### PR DESCRIPTION
**Pull request by johnnewton-hub**
Hi everyone,

Please help me sort this monster.  The preview was misbehaving, so I've left this as a draft for now.  Super busy here, any help greatly appreciated.

### CODE REVIEW

**Comment by ajyong** [comment]
To speed it up, I'll make direct edits and you can view each commit's diff to learn how each small change was made

image

**Comment by ajyong** [comment]
@johnny-newton I've made what edits I think are safe to do!  

One thing though: we listed the 4 problem areas but don't have one for the Popular Choice winner.  I was thinking the easiest thing is to add Popular Choice below our 4 problem areas and just duplicate Covtrace's blurb from their [Runner up section](https://deploy-preview-118--codevid-19-staging.netlify.app/2020/05/16/winners-blog#understanding-the-pandemic).  Thoughts?

**Comment by johnnewton-hub** [comment]
I have that info. Sorry dog ate brain. I'll jump in in 15.  Thanks kindly sir!

**Comment by johnnewton-hub** [comment]
Agreed,
jn

> @johnny-newton I've made what edits I think are safe to do!
> 
> One thing though: we listed the 4 problem areas but don't have one for the Popular Choice winner. I was thinking the easiest thing is to add Popular Choice below our 4 problem areas and just duplicate Covtrace's blurb from their [Runner up section](https://deploy-preview-118--codevid-19-staging.netlify.app/2020/05/16/winners-blog#understanding-the-pandemic). Thoughts?

**Review by johnnewton-hub — COMMENTED** [review]
I've made the corrections that I think this post needed. Please have one final check and I'll send this off. thx, jn

**Review by ajyong — APPROVED** [review]
Looks good!

**Review by johnnewton-hub — COMMENTED** [review]
Thanks Aaron-rough day at the job today for me, omg i forgot the file type...Beers on me when things shake out.

**Pull request merged**
