### PR TITLE
Create 2020-04-29-Amii-guest-blog.md

### PR DESCRIPTION
**Pull request by johnnewton-hub**
https://deploy-preview-112--codevid-19-staging.netlify.app/2020/04/29/amii-guest-blog

### CODE REVIEW

**Comment by johnnewton-hub** [comment]
front matter messed up...do you know why @MarkBennett

**Comment by MarkBennett** [comment]
> front matter messed up...do you know why @MarkBennett 

I'll take a look...

**Comment by MarkBennett** [comment]
It looks like you used capitals instead of lower case for the names of the values in your front matter @johnny-newton.

Change them to lower case `author` and `title` and I'm guessing it will be fine.

**Comment by johnnewton-hub** [comment]
thanks that thing always auto capitalizes-stoops

**Comment by johnnewton-hub** [comment]
that's the ticket Sir!

**Comment by MarkBennett** [comment]
The copy looks good to me, going to do a second pass to double-check grammar, spelling.

Is there an image we could include in this somewhere? Perhaps an Amii logo, or a picture of Edmonton?

**Comment by johnnewton-hub** [comment]
We could drop a photo in there. Logo might be better.  In a case like this, can I add to the file using the "changed files" tab? If so, what is the path to the logo (is it via the dev repo) or somewhere else? Lastly, where would we drop it in?

**Comment by MarkBennett** [comment]
> We could drop a photo in there. Logo might be better. In a case like this, can I add to the file using the "changed files" tab? If so, what is the path to the logo (is it via the dev repo) or somewhere else? Lastly, where would we drop it in?

@johnny-newton If you upload a file here using the "Upload File" button then it will get added to this PR.

https://github.com/johnny-newton/codevid19.com/tree/Amii-guest-blog/images/blog

To access it add something like:

    <span class="image left">Amii Logo</span>

You'd want to replace the `src` and `alt` with a link and description that matches the image.

**Comment by johnnewton-hub** [comment]
HI @MarkBennett  It looks way better now.  Is there a way to get into the front matter- default css code  and make the headline a bit smaller, so it doesn't wrap around? My only beef right now.

**Comment by MarkBennett** [comment]
You can definitely edit the CSS, but it's site wide so we might want to double check what it does before we do that.

Can I suggest we make that another PR @johnny-newton?

**Review by MarkBennett — APPROVED** [review]
Ship it @johnny-newton! 🚢

**Comment by johnnewton-hub** [comment]
Yes, that's probably a good idea.  I don't want to dig into the CSS (totally ignorant), and this should really get up ASAP.  I haven't looked at the analytics to see how much traffic the blog is getting, curious to see.

**Pull request merged**
