### PR TITLE
Amii blog v2

### PR DESCRIPTION
**Pull request by johnnewton-hub**
Hi @MarkBennett , this should be it.

### CODE REVIEW

**Comment by johnnewton-hub** [comment]
nope-it's still there...

**Review by MarkBennett — CHANGES_REQUESTED** [review]
I'm still seeing the image in th excerpt @johnny-newton.

https://deploy-preview-113--codevid-19-staging.netlify.app/blog

Might need to move down a little more.

**Comment by johnnewton-hub** [comment]
Mischief managed!  https://deploy-preview-113--codevid-19-staging.netlify.app/   It required a space before the opening para, and after.

**Review by johnnewton-hub — COMMENTED** [review]
This looks good now, your change was made...

**Review by MarkBennett — APPROVED** [review]
Took me a minute to spot the changes. Looks good now @johnny-newton!

Ship it!

**Pull request merged**
