### PR TITLE
Allow Jekyll to generate excerpts by moving images

### PR DESCRIPTION
**Pull request by ajyong**
This is temporary but allows us to link to our blog listing page without needing to mess with its layout for now.  I'm learning that Jekyll auto-generates excerpts based on the first paragraph, but it doesn't seem to like HTML images being the "first paragraph" much.

### Blog Listing
image
image

### Hello World
image
image

### Charity Exchange
image
image

## Another Proposal
I understand we can also define our own `excerpt` in a front matter variable, but that feels like an extra effort at times and I don't know if we want to enforce that.

image
image

### CODE REVIEW

**Comment by johnnewton-hub** [comment]
I prefer the image nested inside the text-some text above the image and then down the side (the "after" screen shot)- it somehow looks integrated better.  If it's automatic that's a bonus in my pre-professional stage of dev development.  I'm a bit choked that the image is so small-I think it's really a good shot, but I'm not going to debate artistic/design choices, I have a minimal design bg-just know what i like. So I guess you two battle it out!  good night

**Review by johnnewton-hub — COMMENTED** [review]
see comments below...it's a cliff hanger..

**Comment by MarkBennett** [comment]
I'll have to check this out locally and play with this.

Might be able to tweak the image size a bit with the CSS @johnny-newton.

**Comment by johnnewton-hub** [comment]
Hi Mark, thanks for considering image size-your feeling it too I bet?  In the interest of speed, do you want me to merge, and you folks can sort it later with a PR? Impressive new knowledge chops amirite?  I can't wait to hit merge again-I'm aiming for one a day as a new personal best-baby steps folks.

**Comment by ajyong** [comment]
If possible I'd like to at least merge this and get on with other work.  At the current moment, I don't feel we can add the blog as a publicly listed link until the excerpt bug has been worked around.

**Comment by johnnewton-hub** [comment]
So I can hit squash and merge then?

**Comment by ajyong** [comment]
Nope.  The PR author is the one responsible for hitting the button, and I'm still waiting on Mark or another developer who can check this out locally and verify that it works on their machine.

**Review by MarkBennett — APPROVED** [review]
I'm satisfied these are a reasonable workaround for now.

Let's worry about the images sizes in a seperate PR as that's orthogonal to fixing the excerpts. We need to get that blog listing working so we can share it.

**Comment by johnnewton-hub** [comment]
Agreed, don't let perfect get in the way of "the good".

**Review by MandyMeindersma — APPROVED** [review]

**Pull request merged**
