### PR TITLE
Surroung the blog post title in quotes ("")

### PR DESCRIPTION
**Pull request by MarkBennett**
Without these quotes the `:` in the title confuses the blog as the `:` is also used to seperate the data from the property name.

### CODE REVIEW

**Comment by MarkBennett** [comment]
Hey @johnny-newton!

Just a heads up that if you're using a colon in the front matter of a markdown file, the part at the top of the file with the `---` around it, then you need to include quotes `"` around the actual value otherwise the parser will get confused.

**Comment by johnnewton-hub** [comment]
Thx I’ll watch for that..another template battle I imagine. 

jn

**Comment by MarkBennett** [comment]
@johnny-newton just a heads up that if you're good with this change you need to go to the `Files Changed` tab at the top of this Pull Request and click the `Review Changes` button to approve this PR.

**Review by johnnewton-hub — APPROVED** [review]

**Comment by johnnewton-hub** [comment]
It's approved.  S + Merge?

**Comment by MarkBennett** [comment]
Shipped @johnny-newton! Your blog post should now show up on the website:

https://codevid19.com/2020/04/21/week5-winner.html

**Pull request merged**
